"""
Report Generator Module
Generates formatted output from consensus reports.
"""

from typing import List, Dict, Any, Optional
from datetime import datetime


class ReportGenerator:
    """
    Generates formatted reports from consensus data.

    Produces both markdown and structured output formats.
    Language/framework agnostic.
    """

    def __init__(self, config: Optional[Dict[str, Any]] = None):
        self.config = config or {}

    def generate(self, report: Any) -> str:
        """
        Generate markdown report.

        Args:
            report: ConsensusReport object

        Returns:
            Markdown formatted string
        """
        lines = []

        # Header
        lines.append("# Multi-Agent Code Review Report")
        lines.append("")

        # Metadata
        if hasattr(report, "generated_at"):
            lines.append(f"*Generated: {report.generated_at}*")
            lines.append("")

        # Executive Summary
        lines.append("## Executive Summary")
        lines.append(report.summary)
        lines.append("")

        # Get findings by severity
        severity_findings = self._group_by_severity(report.findings)

        # Critical Issues
        if severity_findings["critical"]:
            lines.append(
                f"## 🚨 Critical Issues ({len(severity_findings['critical'])})"
            )
            lines.append("")
            lines.append(
                "These issues require immediate attention and must be fixed before merge."
            )
            lines.append("")
            for i, finding in enumerate(severity_findings["critical"], 1):
                lines.extend(self._format_finding(finding, i))
            lines.append("")

        # High Issues
        if severity_findings["high"]:
            lines.append(
                f"## ⚠️ High Priority Issues ({len(severity_findings['high'])})"
            )
            lines.append("")
            lines.append("These issues should be addressed before merge.")
            lines.append("")
            for i, finding in enumerate(severity_findings["high"], 1):
                lines.extend(self._format_finding(finding, i))
            lines.append("")

        # Consensus Items
        if report.consensus_items:
            lines.append(f"## ✅ Consensus Findings ({len(report.consensus_items)})")
            lines.append("")
            lines.append(
                "These issues were identified by multiple agents and have high confidence:"
            )
            lines.append("")
            for item in report.consensus_items:
                lines.extend(self._format_consensus_item(item))
            lines.append("")

        # Medium Issues
        if severity_findings["medium"]:
            count = len(severity_findings["medium"])
            show_count = min(count, 10)
            lines.append(f"## ℹ️ Medium Priority Issues ({count})")
            lines.append("")
            for i, finding in enumerate(severity_findings["medium"][:show_count], 1):
                lines.extend(self._format_finding(finding, i))
            if count > show_count:
                lines.append(f"*... and {count - show_count} more*")
            lines.append("")

        # Low Issues
        if severity_findings["low"]:
            count = len(severity_findings["low"])
            show_count = min(count, 5)
            lines.append(f"## 💡 Suggestions ({count})")
            lines.append("")
            for i, finding in enumerate(severity_findings["low"][:show_count], 1):
                lines.extend(self._format_finding(finding, i))
            if count > show_count:
                lines.append(f"*... and {count - show_count} more*")
            lines.append("")

        # Statistics
        if hasattr(report, "review_stats") and report.review_stats:
            lines.append("## Review Statistics")
            lines.append("")
            stats = report.review_stats
            lines.append(
                f"- **Execution Time:** {stats.get('execution_time_seconds', 'N/A')}s"
            )
            lines.append(
                f"- **Agents:** {stats.get('agents_success', 0)}/{stats.get('agents_total', 0)} successful"
            )
            lines.append(f"- **Total Findings:** {len(report.findings)}")
            lines.append(f"- **Consensus Items:** {len(report.consensus_items)}")
            lines.append("")

        # Footer
        lines.append("---")
        lines.append("*Report generated by Multi-Agent Code Review Skill*")

        return "\n".join(lines)

    def _group_by_severity(self, findings: List[Any]) -> Dict[str, List[Any]]:
        """Group findings by severity."""
        groups = {"critical": [], "high": [], "medium": [], "low": []}
        for finding in findings:
            severity = (
                finding.severity
                if hasattr(finding, "severity")
                else finding.get("severity", "low")
            )
            if severity in groups:
                groups[severity].append(finding)
        return groups

    def _format_finding(self, finding: Any, index: int) -> List[str]:
        """Format a single finding."""
        lines = []

        # Extract attributes (handle both object and dict)
        if hasattr(finding, "to_dict"):
            f = finding.to_dict()
        else:
            f = finding

        category = f.get("category", "general").upper()
        location = f.get("location", "unknown")
        description = f.get("description", "")
        recommendation = f.get("recommendation", "")
        code_suggestion = f.get("code_suggestion")
        agent = f.get("agent", "unknown")
        confidence = f.get("confidence", 80)

        lines.append(f"### {index}. [{category}] {location}")
        lines.append(f"**Agent:** {agent} (confidence: {confidence}%)")
        lines.append("")
        lines.append(description)
        lines.append("")
        lines.append(f"**Recommendation:** {recommendation}")

        if code_suggestion:
            lines.append("")
            lines.append("**Suggested Fix:**")
            lines.append("```")
            lines.append(code_suggestion)
            lines.append("```")

        # Show alternative recommendations if present
        metadata = f.get("metadata", {})
        alt_recs = metadata.get("alternative_recommendations", [])
        if alt_recs:
            lines.append("")
            lines.append("**Alternative Approaches:**")
            for rec in alt_recs:
                lines.append(f"- {rec}")

        lines.append("")
        return lines

    def _format_consensus_item(self, item: Dict[str, Any]) -> List[str]:
        """Format a consensus item."""
        lines = []

        severity = item.get("severity", "unknown").upper()
        category = item.get("category", "general").upper()
        description = item.get("description", "")
        agents = item.get("agents", [])
        count = item.get("agreement_count", len(agents))

        lines.append(f"### [{severity}] {category}")
        lines.append(f"**✅ {count} agents agree:** {', '.join(agents)}")
        lines.append("")
        lines.append(description)
        lines.append("")

        if item.get("recommendation"):
            lines.append(f"**Recommendation:** {item['recommendation']}")

        if item.get("code_suggestion"):
            lines.append("")
            lines.append("**Suggested Code:**")
            lines.append("```")
            lines.append(item["code_suggestion"])
            lines.append("```")

        lines.append("")
        return lines
